import { TrainingTask } from './types';

export const weeklyTraining: { [week: number]: TrainingTask[] } = {
  1: [
    { id: 'w1t1', title: 'Husky-proof your home and yard', description: 'Secure fencing (6ft minimum), remove hazards, check for escape routes. Huskies are expert escape artists!', category: 'Crate Training', difficulty: 'Easy', completed: false },
    { id: 'w1t2', title: 'Establish strict routine from day one', description: 'Huskies thrive on consistency. Set feeding times (3x daily for puppies), potty breaks every 2 hours, and regular nap times.', category: 'Obedience', difficulty: 'Easy', completed: false },
    { id: 'w1t3', title: 'Set up a secure crate setup', description: 'Choose a sturdy crate where puppy can see family. Huskies need den-like spaces for security.', category: 'Crate Training', difficulty: 'Easy', completed: false },
    { id: 'w1t4', title: 'Schedule first vet visit and discuss exercise needs', description: 'Get health check, vaccinations, and discuss husky-specific health concerns and exercise requirements.', category: 'Socialization', difficulty: 'Easy', completed: false },
    { id: 'w1t5', title: 'Name recognition training', description: 'Use puppy\'s name positively with high-value treats. Critical foundation for recall training with huskies.', category: 'Obedience', difficulty: 'Easy', completed: false },
    { id: 'w1t6', title: 'Crate training with positive association', description: 'Feed meals inside, use Kong toys, never use as punishment. Start with 5-10 minute sessions.', category: 'Crate Training', difficulty: 'Medium', completed: false },
    { id: 'w1t7', title: 'Begin gentle handling exercises', description: 'Touch paws, ears, tail, and mouth daily. Prepares for grooming and builds trust.', category: 'Socialization', difficulty: 'Easy', completed: false },
  ],
  2: [
    { id: 'w2t1', title: 'Intensive potty training schedule', description: 'Take out every 1-2 hours, immediately after meals, play, and waking. Use consistent "potty" command. Huskies learn quickly with consistency.', category: 'Potty Training', difficulty: 'Medium', completed: false },
    { id: 'w2t2', title: 'Teach "Sit" with high-value rewards', description: 'Use chicken, cheese, or freeze-dried liver. Huskies can be stubborn - make it worth their while! Practice 3-5 minute sessions, 4-5 times daily.', category: 'Obedience', difficulty: 'Easy', completed: false },
    { id: 'w2t3', title: 'Establish firm house rules', description: 'Huskies will test boundaries! Decide on rules (furniture, rooms, etc.) and enforce consistently with all family members.', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w2t4', title: 'Practice calm greetings', description: 'Huskies are excitable! Ignore jumping, reward four paws on floor. Practice with family members multiple times daily.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w2t5', title: 'Bite inhibition with vocal feedback', description: 'Huskies are mouthy! Yelp loudly when bitten, redirect to toys. End playtime if biting continues. Practice gentle mouth exercises.', category: 'Chewing/Biting', difficulty: 'Medium', completed: false },
    { id: 'w2t6', title: 'Sound desensitization training', description: 'Huskies can be reactive to sounds. Gradually expose to vacuum, doorbell, TV at low volume with treats and calm energy.', category: 'Socialization', difficulty: 'Easy', completed: false },
    { id: 'w2t7', title: 'Start mental stimulation games', description: 'Hide treats in towels, use puzzle feeders. Huskies need mental exercise to prevent destructive behavior.', category: 'Obedience', difficulty: 'Easy', completed: false },
  ],
  3: [
    { id: 'w3t1', title: 'Collar and harness introduction', description: 'Introduce both collar and harness (use harness for walks to prevent pulling). Let puppy adjust indoors with positive reinforcement.', category: 'Obedience', difficulty: 'Easy', completed: false },
    { id: 'w3t2', title: 'Indoor leash walking foundation', description: 'Practice loose leash walking indoors. Huskies are natural pullers - start teaching early! Stop when they pull, reward slack leash.', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w3t3', title: 'Start recall training (critical for huskies!)', description: 'Practice "Come" in enclosed space with irresistible treats. NEVER punish when they come. Make it the best thing ever! Use long line outdoors.', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w3t4', title: 'Potty training consistency', description: 'Maintain rigid schedule, use specific potty spot, high-value rewards immediately after. Clean accidents with enzyme cleaner.', category: 'Potty Training', difficulty: 'Medium', completed: false },
    { id: 'w3t5', title: 'Controlled socialization with people', description: 'Invite calm, dog-savvy friends over. Teach puppy to sit for greeting. Keep sessions short (10-15 min) to prevent overstimulation.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w3t6', title: 'Extended crate time training', description: 'Build up to 30-45 minutes. Leave special toys only available in crate. Practice leaving and returning calmly.', category: 'Crate Training', difficulty: 'Medium', completed: false },
    { id: 'w3t7', title: 'Teach "Watch me" command', description: 'Get eye contact on command - essential for husky focus with distractions. Use high-value treats, start in quiet environment.', category: 'Obedience', difficulty: 'Medium', completed: false },
  ],
  4: [
    { id: 'w4t1', title: 'First outdoor exploration walks', description: 'After vaccinations complete, start 10-15 min walks. Let puppy sniff and explore. Use harness to manage pulling. 2-3 walks daily.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w4t2', title: 'Teach "Down" command', description: 'Lure from sit with treat to floor. Huskies may resist - be patient! Use relaxation protocol. Practice 3-4 times daily.', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w4t3', title: 'Car training for travel', description: 'Essential for vet visits and adventures. Start with car off, then running, then short trips. Use crate or car harness for safety.', category: 'Socialization', difficulty: 'Easy', completed: false },
    { id: 'w4t4', title: 'Master "Leave it" command', description: 'CRITICAL for husky safety due to prey drive. Practice with treats, toys, then outdoor items. Never let them "steal" the item!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w4t5', title: 'Redirect destructive chewing', description: 'Provide frozen Kongs, bully sticks, chew toys. Huskies need appropriate outlets! Supervise and redirect to approved items.', category: 'Chewing/Biting', difficulty: 'Medium', completed: false },
    { id: 'w4t6', title: 'Overnight crate confidence', description: 'Work toward sleeping 6-8 hours. Last potty break at 11pm, first break at 6-7am. No play during night breaks!', category: 'Crate Training', difficulty: 'Hard', completed: false },
    { id: 'w4t7', title: 'Boundary training begins', description: 'Teach "wait" at doors and gates. Huskies are escape artists - this is crucial! Practice every door exit.', category: 'Obedience', difficulty: 'Medium', completed: false },
  ],
  5: [
    { id: 'w5t1', title: 'Introduce "Stay" with duration', description: 'Start with 3-5 seconds, build to 30 seconds. Use release word ("okay" or "free"). Huskies get bored easily - keep exciting!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w5t2', title: 'Loose leash walking practice', description: 'Practice daily! Stop immediately when pulling, reward position by your side. Consider front-clip harness. Be patient - this takes time!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w5t3', title: 'Controlled dog socialization', description: 'Meet vaccinated, friendly dogs in controlled settings. Watch body language. Huskies can be dog-selective as adults. Short 10-15 min sessions.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w5t4', title: 'Perfect "Drop it" command', description: 'Trade for better treat/toy. Essential due to prey drive and tendency to grab things. Practice with favorite toys and random objects.', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w5t5', title: 'Surface and texture exposure', description: 'Walk on grass, gravel, sand, tile, wood, metal grates, stairs. Build confidence on all surfaces. Important for husky adventures!', category: 'Socialization', difficulty: 'Easy', completed: false },
    { id: 'w5t6', title: 'Potty training near completion', description: 'Most accidents should be eliminated. Puppy should signal when needs to go. Maintain schedule for consistency.', category: 'Potty Training', difficulty: 'Medium', completed: false },
    { id: 'w5t7', title: 'Advanced mental stimulation', description: 'Introduce snuffle mats, advanced puzzle toys, hide-and-seek games. Tire the husky mind to prevent mischief!', category: 'Obedience', difficulty: 'Easy', completed: false },
  ],
  6: [
    { id: 'w6t1', title: 'Commands with moderate distractions', description: 'Practice sit, stay, down, come with people walking by, toys present. Build husky focus despite distractions.', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w6t2', title: 'Novel environment exposure', description: 'Visit pet stores, outdoor cafes, parks, hiking trails. Huskies love new places! Keep on leash always. Bring water.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w6t3', title: 'Door manners and boundary respect', description: 'Must sit and wait at all doorways before permission to exit. Critical for preventing escapes! Practice 10+ times daily.', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w6t4', title: 'Complete grooming desensitization', description: 'Brush 3-4 times weekly (blowing season ahead!), handle paws for nail trims, check ears. Make it pleasant with treats.', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w6t5', title: 'Impulse control exercises', description: 'Wait for food bowl, zen game (treat on paw), calm greetings. Huskies are impulsive - this is crucial training!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w6t6', title: 'Soft mouth and bite inhibition completion', description: 'No hard bites tolerated. Any pressure from teeth = immediate cessation of play. Should be nearly perfect by now.', category: 'Chewing/Biting', difficulty: 'Medium', completed: false },
    { id: 'w6t7', title: 'Start "quiet" command training', description: 'Huskies are VOCAL! Teach bark/howl on command, then teach "quiet". Reward silence generously.', category: 'Obedience', difficulty: 'Hard', completed: false },
  ],
  7: [
    { id: 'w7t1', title: 'Increase exercise duration', description: 'Build to 20-30 minute walks, 2-3 times daily. Add jogging if old enough. Huskies need significant exercise! Mental stimulation counts too.', category: 'Socialization', difficulty: 'Easy', completed: false },
    { id: 'w7t2', title: 'Long-line recall training', description: 'Use 20-30ft line in safe area. Practice recall with increasing distance. NEVER off-leash unless securely fenced. Husky recall is challenging!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w7t3', title: 'Fun trick training', description: 'Shake, spin, rollover, play dead, speak. Keeps training fun! Huskies are smart and enjoy learning new things.', category: 'Obedience', difficulty: 'Easy', completed: false },
    { id: 'w7t4', title: 'Supervised child socialization', description: 'Teach gentle interaction with children. Huskies can be great with kids but need boundaries. Always supervise!', category: 'Socialization', difficulty: 'Hard', completed: false },
    { id: 'w7t5', title: 'Place/mat training in public', description: 'Teach "place" command to relax on mat/bed in various locations. Great for outdoor dining, visits, etc.', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w7t6', title: 'House-training mastery', description: 'Should be fully reliable now. Can signal need to go out. Rare accidents only. Celebrate this achievement!', category: 'Potty Training', difficulty: 'Medium', completed: false },
    { id: 'w7t7', title: 'Introduce backpack walks', description: 'Start with empty dog backpack to get used to it. Next week add light weight. Great for channeling working dog energy!', category: 'Socialization', difficulty: 'Easy', completed: false },
  ],
  8: [
    { id: 'w8t1', title: 'Proof all basic commands', description: 'Sit, down, stay, come, leave it, drop it should be reliable in various settings with distractions. Daily practice!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w8t2', title: 'Master distraction-level walking', description: 'Walk calmly past dogs, people, bikes, squirrels, birds. Use "watch me" and "leave it" commands. Celebrate progress!', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w8t3', title: 'Enroll in advanced puppy class', description: 'Group training class provides socialization and structure. Look for husky-experienced trainers. Consider agility or nosework!', category: 'Socialization', difficulty: 'Medium', completed: false },
    { id: 'w8t4', title: 'Generalize commands everywhere', description: 'Practice all commands in new locations: different parks, stores, trails, friends\' houses. Huskies need to learn commands work everywhere.', category: 'Obedience', difficulty: 'Hard', completed: false },
    { id: 'w8t5', title: 'Comprehensive training review', description: 'Assess progress in all areas. Identify weak spots. Celebrate successes! Your husky has come so far!', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w8t6', title: 'Establish lifelong routine', description: 'Daily: 2-3 walks (30+ min), mental games, training practice. Weekly: new environments, socialization. Huskies need lifetime enrichment!', category: 'Obedience', difficulty: 'Medium', completed: false },
    { id: 'w8t7', title: 'Plan for adolescence (4-18 months)', description: 'Research adolescent phase challenges. Maintain consistency! Join husky communities. Consider ongoing training classes. The journey continues!', category: 'Obedience', difficulty: 'Medium', completed: false },
  ],
};
